trigger:
- main

pool:
  name: VCPTeamPool

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Write-Host "Hello World"
      Get-ChildItem $(Build.SourcesDirectory)
