name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build detekt validatePlugins
      - name: Build plugin usage with groovy test project
        working-directory: ./translations-plugin-gradle-test/groovy/
        run: ./gradlew build
      - name: Build plugin usage with kts test project
        working-directory: ./translations-plugin-gradle-test/kts/
        run: ./gradlew build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true